config/routes.rb
Rails.application.routes.draw do
  root 'homes#top'
  get 'home/about' => 'homes#about', as: 'about'
  devise_for :users
  resources :users, only: [:show,:index,:edit,:update]
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}, uniqueness: true
  attachment :profile_image, destroy: false
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
      render "edit"
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update, :edit]
  
  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render "edit"
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(current_user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book, local:true do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'col-xs-12 book_title' %>
  </div>

  <div class="field row">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'col-xs-12 book_body' %>
  </div>

  <div class="actions row">
    <%= f.submit class: 'btn btn-primary col-xs-12' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
			<h1>Editing Book</h1>
			<%= render 'layouts/errors', obj: @book %>
			<%= render "books/form", book: @book %>
			<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
			<%= link_to "Back", books_path, class: "back" %>
	</div>
</div>

app/views/books/index.html.erb
<%= render 'layouts/errors', obj: @book %>

	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>

			<h2>New book</h2>
			<%= render 'books/form', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books index</h2>
			<!--books一覧 -->
		<%= render 'index', books: @books%>
			<!--books一覧 -->

		</div>
	</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile',user: @user %>

		<h2>New book</h2>
		<%= render 'books/form', book: @new_book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book.title, book_path(@book) %></td>
					<td><%= @book.body %></td>
					
					<% if current_user == @book.user %>
					<td><%= link_to "Edit", edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy", book_path(@book), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
				</tr>
			</table>

	</div>
</div>

app/views/homes/about.html.erb
<div class='about'>
  <div class='about-row'>
    <h1>Welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="row">
  <div class='top-message col-xs-offset-3 col-xs-6'>
    <h1>welcome to <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong> !!</h1>
    <p>In <span class='glyphicon glyphicon-book'></span><strong>Bookers</strong>, </p>
    <p>you can share and exchange your opinions , inpressions , and emotions</p>
    <p> about various books!</p>

    <div class="btn-wrapper">
      <div class="row">
        <p><%= link_to 'Log in', new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1 login-btn" %></p>
      </div>
      <div class="row">
        <p><%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
      </div>
    </div>

  </div>
</div>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>

    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
	<div class='container footer'>
		<div class='footer-row'>
			<div class='copy-right'>
				<p>CopyRight Infratop.inc</p>
			</div>
		</div>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav class='nav navbar-nav navbar-left' >
      <span>Bookers</span>
    </nav>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' Home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' Users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' Books', books_path, class: 'glyphicon glyphicon-book books'%></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
        <% else %>
          <li><%= link_to ' Home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' About', about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in'%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2-debug</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <p id="notice"><%= notice %></p>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
    
  </body>
</html>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
</table>

<div class="row">
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
    
    <%= render 'layouts/errors', obj: @user %>
      
<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>
      
<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">

			<h2>User info</h2>
			
			<%= render 'users/profile', user: current_user %>
			
			<h2>New book</h2>
			<%= render 'books/form', book: @book %>
	</div>
	
	<div class="col-xs-9">
			<h2>Users</h2>
			<%= render 'index',users: @users %>

	</div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		
		<%= render 'books/form', book: @book %>
	</div>

	<div class="col-xs-9">
			<h2>Books</h2>
			<%= render 'books/index',books: @books %>

  </div>
</div>
		